name: CI

on:
  pull_request:
  push:


jobs:
  sanity:
    name: ${{ matrix.test.name }}
    runs-on: ubuntu-20.04
    container:
      image: quay.io/ansible/ansible-runner-test-container:2.0.0
      env:
        PIP_CACHE_DIR: ${{ runner.temp }}/.cache/pip
        PY_COLORS: 1
        TOXENV: ${{ matrix.test.tox_env }}

    strategy:
      fail-fast: false
      matrix:
        test:
          - name: Lint
            tox_env: linters

          - name: Docs
            tox_env: docs

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create tox environment
        run: tox --notest

      - name: Run tests
        run: tox


  integration:
    runs-on: ubuntu-20.04
    name: Integration - ${{ matrix.py_version.name }}

    env:
      TOXENV: ${{ matrix.py_version.tox_env }}
      PY_COLORS: 1

    strategy:
      fail-fast: false
      matrix:
        py_version:
          - name: '3.8'
            tox_env: integration-py38



    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python ${{ matrix.py_version.name }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py_version.name }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          username: shaogd
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Run integration tests
        run: |
          	docker buildx create --use --driver docker-container --name ansible_runner > /dev/null 2>&1 || true
            docker buildx build --platform linux/arm64,linux/amd64 --push \
              --no-cache --build-arg ANSIBLE_BRANCH=stable-2.9 \
              -t shaogd/ansible-runner:release-2.3-stable-2.9 \
              -f Dockerfile --provenance=false \
              .
            docker buildx rm ansible_runner || true





